/**
 * DynamicVideo.tsx — The root Remotion composition for all generated videos.
 * 
 * This component takes the `VideoScript` JSON generated by the backend and 
 * maps it into a Remotion video timeline. It handles:
 * - Iterating through scenes and laying them out in `Sequence`s
 * - Rendering grid layouts (full, left-right, title-main-sidebar, etc.)
 * - Adding theme-driven backgrounds and transition effects
 * - Instantiating the requested components (from `registry.ts`) into grid areas
 * - Rendering on-screen captions synced to narration
 * - Playing the global TTS audio track
 */
import React from "react";
import {
  AbsoluteFill,
  Sequence,
  Easing,
  interpolate,
  useCurrentFrame,
  Audio,
} from "remotion";
import { ThemeProvider, Theme, useTheme } from "./ThemeContext";
import { COMPONENT_REGISTRY, SceneType } from "./registry";
import { Background } from "./components/Background";
import { CaptionLayer } from "./components/CaptionLayer";

const DIAGRAM_TYPES = new Set([
  "ArchitectureDiagram",
  "PacketFlow",
  "HashRing",
  "StateMachine",
  "TreeHierarchy",
  "SequenceDiagram",
  "FlowDiagram",
]);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type TransitionType = "fade" | "slideLeft" | "slideUp" | "zoom" | "none";

type Panel = {
  area: string;
  type: string;
  data: Record<string, unknown>;
};

type SceneSpec = {
  id: string;
  layout?: string;
  title?: string;
  subtitle?: string;
  duration_frames: number;
  transition: TransitionType;
  narration?: string;
  panels?: Panel[];
  // Legacy single-component format (old JSON files)
  type?: string;
  data?: Record<string, unknown>;
};

export type Caption = {
  text: string;
  startMs: number;
  endMs: number;
  timestampMs: number | null;
  confidence: number | null;
};

export type VoiceoverSpec = {
  provider: string | null;
  captions: Caption[];
};

/** Normalise both old {type,data} and new {layout,panels[]} scene shapes. */
function normaliseScene(
  scene: SceneSpec,
): Required<Pick<SceneSpec, "layout" | "title" | "panels">> {
  if (scene.panels && scene.panels.length > 0) {
    return {
      layout: scene.layout ?? "full",
      title: scene.title ?? "",
      panels: scene.panels,
    };
  }
  // Legacy: wrap the single component into a full-layout panel
  return {
    layout: "full",
    title: scene.title ?? "",
    panels: [
      {
        area: "panel",
        type: scene.type ?? "BulletList",
        data: scene.data ?? {},
      },
    ],
  };
}

export type VideoScriptProps = {
  title: string;
  fps: number;
  width: number;
  height: number;
  theme: Theme;
  voiceover?: VoiceoverSpec | null;
  audio_url?: string | null;
  scenes: SceneSpec[];
};

// ---------------------------------------------------------------------------
// Layout system
// ---------------------------------------------------------------------------

const HEADER_H = 148; // px, for title-* layouts

type LayoutConfig = {
  hasHeader: boolean;
  gridTemplateAreas: string;
  gridTemplateColumns: string;
  gridTemplateRows: string;
};

const LAYOUTS: Record<string, LayoutConfig> = {
  full: {
    hasHeader: false,
    gridTemplateAreas: '"panel"',
    gridTemplateColumns: "1fr",
    gridTemplateRows: "1fr",
  },
  "left-right": {
    hasHeader: false,
    gridTemplateAreas: '"left right"',
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr",
  },
  "title-content": {
    hasHeader: true,
    gridTemplateAreas: '"main"',
    gridTemplateColumns: "1fr",
    gridTemplateRows: "1fr",
  },
  "title-left-right": {
    hasHeader: true,
    gridTemplateAreas: '"left right"',
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr",
  },
  "title-main-sidebar": {
    hasHeader: true,
    gridTemplateAreas: '"main sidebar"',
    gridTemplateColumns: "1.85fr 1fr",
    gridTemplateRows: "1fr",
  },
};

// ---------------------------------------------------------------------------
// Scene header bar (rendered by DynamicVideo for title-* layouts)
// ---------------------------------------------------------------------------

const SceneHeader: React.FC<{ title: string; subtitle?: string }> = ({
  title,
  subtitle,
}) => {
  const frame = useCurrentFrame();
  const theme = useTheme();

  const opacity = interpolate(frame, [0, 18], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const translateY = interpolate(frame, [0, 18], [-20, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const lineScaleX = interpolate(frame, [8, 28], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <div
      style={{
        height: HEADER_H,
        padding: "0 72px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        opacity,
        transform: `translateY(${translateY}px)`,
        borderBottom: `1px solid rgba(255,255,255,0.08)`,
        background: `linear-gradient(135deg, ${theme.background} 60%, ${theme.primary}18 100%)`,
        flexShrink: 0,
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
        {/* Accent bar */}
        <div
          style={{
            width: 5,
            height: 44,
            borderRadius: 3,
            background: `linear-gradient(180deg, ${theme.primary}, ${theme.accent})`,
            flexShrink: 0,
            transformOrigin: "top",
            transform: `scaleY(${lineScaleX})`,
          }}
        />
        <div>
          <h2
            style={{
              margin: 0,
              fontSize: 46,
              fontWeight: 800,
              color: "#ffffff",
              letterSpacing: "-0.02em",
              lineHeight: 1.1,
              fontFamily: "inherit",
            }}
          >
            {title}
          </h2>
          {subtitle && (
            <p
              style={{
                margin: "4px 0 0",
                fontSize: 22,
                color: "rgba(255,255,255,0.55)",
                fontWeight: 400,
                letterSpacing: "0.01em",
              }}
            >
              {subtitle}
            </p>
          )}
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Panel renderer — wraps one component in its grid area
// ---------------------------------------------------------------------------

const PanelCell: React.FC<{ panel: Panel; gridArea: string }> = ({
  panel,
  gridArea,
}) => {
  const theme = useTheme();
  const Component = COMPONENT_REGISTRY[panel.type as SceneType];

  const safeProps = Object.fromEntries(
    Object.entries(panel.data).map(([k, v]: [string, unknown]) => [
      k,
      v === null ? undefined : v,
    ]),
  ) as Record<string, unknown>;

  // Thread the theme into every accent-aware component from one place, so the
  // palette the Director picked actually drives the whole video. Components keep
  // their own default if the data already specifies an accentColor.
  if (safeProps.accentColor == null) {
    safeProps.accentColor = theme.primary;
  }

  if (!Component) {
    return (
      <div
        style={{
          gridArea,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px dashed #ef4444",
        }}
      >
        <span style={{ color: "#ef4444", fontSize: 20 }}>
          Unknown: {panel.type}
        </span>
      </div>
    );
  }

  const AnyComponent = Component as React.FC<Record<string, unknown>>;

  return (
    <div style={{ gridArea, position: "relative", overflow: "hidden" }}>
      <AnyComponent {...safeProps} />
    </div>
  );
};

// ---------------------------------------------------------------------------
// SceneWrapper — renders header + grid of panels + transition overlay
// ---------------------------------------------------------------------------

const TRANSITION_FRAMES = 15;

const SceneWrapper: React.FC<{ scene: SceneSpec, videoWidth: number, videoHeight: number }> = ({ scene, videoWidth, videoHeight }) => {
  const { layout, title, panels } = normaliseScene(scene);
  const config = LAYOUTS[layout] ?? LAYOUTS["full"];
  const contentH = config.hasHeader ? videoHeight - HEADER_H : videoHeight;
  const hasDiagram = panels.some((p) => DIAGRAM_TYPES.has(p.type));

  return (
    <AbsoluteFill>
      {/* Animated theme-driven background (behind everything) */}
      <Background variant={hasDiagram ? "grid" : "glow"} />

      {/* Content above the background */}
      <AbsoluteFill style={{ flexDirection: "column", zIndex: 1 }}>
        {/* Header bar */}
        {config.hasHeader && (
          <SceneHeader title={title} subtitle={scene.subtitle} />
        )}

        {/* Content grid */}
        <div
          style={{
            flex: 1,
            height: contentH,
            display: "grid",
            gridTemplateAreas: config.gridTemplateAreas,
            gridTemplateColumns: config.gridTemplateColumns,
            gridTemplateRows: config.gridTemplateRows,
            gap: 0,
          }}
        >
          {panels.map((panel) => (
            <PanelCell key={panel.area} panel={panel} gridArea={panel.area} />
          ))}
        </div>
      </AbsoluteFill>

      {/* Transition overlay */}
      {scene.transition !== "none" && (
        <Sequence
          from={scene.duration_frames - TRANSITION_FRAMES}
          durationInFrames={TRANSITION_FRAMES}
          layout="none"
        >
          <TransitionOverlay transition={scene.transition} />
        </Sequence>
      )}
    </AbsoluteFill>
  );
};

// ---------------------------------------------------------------------------
// Transition overlay
// ---------------------------------------------------------------------------

const TransitionOverlay: React.FC<{ transition: TransitionType }> = ({
  transition,
}) => {
  const frame = useCurrentFrame();
  const theme = useTheme();

  // Smooth 0→1 sweep across the overlay's lifetime (eased, not springy, so the
  // wipe reads as a clean directional motion).
  const p = interpolate(frame, [0, TRANSITION_FRAMES], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.65, 0, 0.35, 1),
  });

  // A themed gradient panel — more cinematic than flat black.
  const panel = `linear-gradient(135deg, ${theme.background} 0%, ${theme.primary}cc 60%, ${theme.accent}aa 100%)`;

  if (transition === "fade") {
    const fadeOpacity = interpolate(
      frame,
      [0, TRANSITION_FRAMES / 2, TRANSITION_FRAMES],
      [0, 0.95, 0],
      { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
    );
    return (
      <AbsoluteFill
        style={{
          background: panel,
          opacity: fadeOpacity,
          pointerEvents: "none",
        }}
      />
    );
  }
  if (transition === "slideLeft") {
    // Wipe in from the right, covering the outgoing scene.
    return (
      <AbsoluteFill
        style={{
          background: panel,
          transform: `translateX(${interpolate(p, [0, 1], [100, 0])}%)`,
          pointerEvents: "none",
        }}
      />
    );
  }
  if (transition === "slideUp") {
    return (
      <AbsoluteFill
        style={{
          background: panel,
          transform: `translateY(${interpolate(p, [0, 1], [100, 0])}%)`,
          pointerEvents: "none",
        }}
      />
    );
  }
  if (transition === "zoom") {
    // Radial flash that scales up — for the most dramatic beat.
    const flash = interpolate(
      frame,
      [0, TRANSITION_FRAMES / 2, TRANSITION_FRAMES],
      [0, 0.85, 0],
      { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
    );
    return (
      <AbsoluteFill
        style={{
          background: `radial-gradient(circle at 50% 50%, ${theme.accent}, ${theme.primary} 50%, ${theme.background} 100%)`,
          opacity: flash,
          transform: `scale(${interpolate(p, [0, 1], [1, 1.12])})`,
          pointerEvents: "none",
        }}
      />
    );
  }
  return null;
};

// ---------------------------------------------------------------------------
// DynamicVideo — top-level composition
// ---------------------------------------------------------------------------

export const DynamicVideo: React.FC<VideoScriptProps> = ({
  width,
  height,
  theme,
  scenes,
  voiceover,
  audio_url,
}) => {
  let cursor = 0;
  const positioned = scenes.map((scene) => {
    const from = cursor;
    cursor += scene.duration_frames;
    return { scene, from };
  });

  return (
    <ThemeProvider theme={theme}>
      <AbsoluteFill style={{ backgroundColor: theme.background }}>
        {positioned.map(({ scene, from }) => (
          <Sequence
            key={scene.id}
            from={from}
            durationInFrames={scene.duration_frames}
            premountFor={30}
          >
            <SceneWrapper scene={scene} videoWidth={width} videoHeight={height} />
          </Sequence>
        ))}

        {/* Global TTS Audio */}
        {audio_url && <Audio src={`http://127.0.0.1:8000${audio_url}`} />}

        {/* On-screen textual explanation (narration), synced to the absolute timeline */}
        <CaptionLayer captions={voiceover?.captions} />
      </AbsoluteFill>
    </ThemeProvider>
  );
};
