/**
 * DynamicVideo.tsx — The root Remotion composition for all generated videos.
 *
 * This component takes the `VideoScript` JSON generated by the backend and
 * maps it into a Remotion video timeline. It handles:
 * - Iterating through scenes and laying them out in `Sequence`s
 * - Rendering grid layouts (full, left-right, title-main-sidebar, etc.)
 * - Adding theme-driven backgrounds and transition effects
 * - Instantiating the requested components (from `registry.ts`) into grid areas
 * - Rendering on-screen captions synced to narration
 * - Playing the global TTS audio track
 */
import React from "react";
import {
  AbsoluteFill,
  Sequence,
  interpolate,
  useCurrentFrame,
  Audio,
} from "remotion";
import { ThemeProvider, Theme, useTheme } from "./ThemeContext";
import { COMPONENT_REGISTRY, SceneType } from "./registry";
import { Background } from "./components/Background";
import { CaptionLayer } from "./components/CaptionLayer";
import { PanelSizeProvider } from "./PanelSizeContext";
import { computeFractions, cellWidths } from "./layout";

// Reserve a band at the bottom of a scene for the caption/subtitle so panels
// never render on top of or below it (CaptionLayer draws inside this band).
// Only applied when the video actually has captions; otherwise panels get the
// full height. Kept just tall enough for a two-line caption at the very bottom.
const SUBTITLE_RESERVE_FRAC = 0.13; // ~140px on 1080p

const DIAGRAM_TYPES = new Set([
  "ArchitectureDiagram",
  "PacketFlow",
  "HashRing",
  "StateMachine",
  "TreeHierarchy",
  "SequenceDiagram",
  "FlowDiagram",
]);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type TransitionType = "fade" | "slideLeft" | "slideUp" | "zoom" | "none";

type Panel = {
  area: string;
  type: string;
  size_ratio?: number;
  delay_frames?: number;
  data: Record<string, unknown>;
};

type SceneSpec = {
  id: string;
  layout?: string;
  title?: string;
  subtitle?: string;
  duration_frames: number;
  transition: TransitionType;
  narration?: string;
  panels?: Panel[];
  // Legacy single-component format (old JSON files)
  type?: string;
  data?: Record<string, unknown>;
};

export type Caption = {
  text: string;
  startMs: number;
  endMs: number;
  timestampMs: number | null;
  confidence: number | null;
};

export type VoiceoverSpec = {
  provider: string | null;
  captions: Caption[];
};

/** Normalise both old {type,data} and new {layout,panels[]} scene shapes. */
function normaliseScene(
  scene: SceneSpec,
): Required<Pick<SceneSpec, "layout" | "title" | "panels">> {
  if (scene.panels && scene.panels.length > 0) {
    return {
      layout: scene.layout ?? "full",
      title: scene.title ?? "",
      panels: scene.panels,
    };
  }
  // Legacy: wrap the single component into a full-layout panel
  return {
    layout: "full",
    title: scene.title ?? "",
    panels: [
      {
        area: "panel",
        type: scene.type ?? "BulletList",
        data: scene.data ?? {},
      },
    ],
  };
}

export type VideoScriptProps = {
  title: string;
  fps: number;
  width: number;
  height: number;
  theme: Theme;
  voiceover?: VoiceoverSpec | null;
  audio_url?: string | null;
  scenes: SceneSpec[];
};

// ---------------------------------------------------------------------------
// Layout system
// ---------------------------------------------------------------------------

const HEADER_H = 148; // px, for title-* layouts

type LayoutConfig = {
  hasHeader: boolean;
  gridTemplateAreas: string;
  gridTemplateColumns: string;
  gridTemplateRows: string;
};

const LAYOUTS: Record<string, LayoutConfig> = {
  full: {
    hasHeader: false,
    gridTemplateAreas: '"panel"',
    gridTemplateColumns: "1fr",
    gridTemplateRows: "1fr",
  },
  "left-right": {
    hasHeader: false,
    gridTemplateAreas: '"left right"',
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr",
  },
  "title-content": {
    hasHeader: true,
    gridTemplateAreas: '"main"',
    gridTemplateColumns: "1fr",
    gridTemplateRows: "1fr",
  },
  "title-left-right": {
    hasHeader: true,
    gridTemplateAreas: '"left right"',
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr",
  },
  "title-main-sidebar": {
    hasHeader: true,
    gridTemplateAreas: '"main sidebar"',
    gridTemplateColumns: "1.85fr 1fr",
    gridTemplateRows: "1fr",
  },
};

// ---------------------------------------------------------------------------
// Scene header bar (rendered by DynamicVideo for title-* layouts)
// ---------------------------------------------------------------------------

const SceneHeader: React.FC<{ title: string; subtitle?: string }> = ({
  title,
  subtitle,
}) => {
  const frame = useCurrentFrame();
  const theme = useTheme();

  const opacity = interpolate(frame, [0, 18], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const translateY = interpolate(frame, [0, 18], [-20, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const lineScaleX = interpolate(frame, [8, 28], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <div
      style={{
        height: HEADER_H,
        padding: "0 72px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        opacity,
        transform: `translateY(${translateY}px)`,
        borderBottom: `1px solid rgba(255,255,255,0.08)`,
        background: `linear-gradient(135deg, ${theme.background} 60%, ${theme.primary}18 100%)`,
        flexShrink: 0,
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
        {/* Accent bar */}
        <div
          style={{
            width: 5,
            height: 44,
            borderRadius: 3,
            background: `linear-gradient(180deg, ${theme.primary}, ${theme.accent})`,
            flexShrink: 0,
            transformOrigin: "top",
            transform: `scaleY(${lineScaleX})`,
          }}
        />
        <div>
          <h2
            style={{
              margin: 0,
              fontSize: 46,
              fontWeight: 800,
              color: "#ffffff",
              letterSpacing: "-0.02em",
              lineHeight: 1.1,
              fontFamily: "inherit",
            }}
          >
            {title}
          </h2>
          {subtitle && (
            <p
              style={{
                margin: "4px 0 0",
                fontSize: 22,
                color: "rgba(255,255,255,0.55)",
                fontWeight: 400,
                letterSpacing: "0.01em",
              }}
            >
              {subtitle}
            </p>
          )}
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Panel renderer — wraps one component in its grid area
// ---------------------------------------------------------------------------

const PanelCell: React.FC<{
  panel: Panel;
  gridArea: string;
  cellW: number;
  cellH: number;
}> = ({ panel, gridArea, cellW, cellH }) => {
  const theme = useTheme();
  const Component = COMPONENT_REGISTRY[panel.type as SceneType];

  const safeProps = Object.fromEntries(
    Object.entries(panel.data).map(([k, v]: [string, unknown]) => [
      k,
      v === null ? undefined : v,
    ]),
  ) as Record<string, unknown>;

  // Thread the theme into every accent-aware component from one place, so the
  // palette the Director picked actually drives the whole video. Components keep
  // their own default if the data already specifies an accentColor.
  if (safeProps.accentColor == null) {
    safeProps.accentColor = theme.primary;
  }

  if (!Component) {
    return (
      <div
        style={{
          gridArea,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px dashed #ef4444",
        }}
      >
        <span style={{ color: "#ef4444", fontSize: 20 }}>
          Unknown: {panel.type}
        </span>
      </div>
    );
  }

  const AnyComponent = Component as React.FC<Record<string, unknown>>;
  const { style, ...componentProps } = safeProps;

  // Cell-responsive: the component renders at its cell's actual pixel size and is
  // told that size via PanelSizeProvider, so it fills and reflows at natural font
  // sizes instead of being scaled down. overflow:hidden guards any residual spill.
  return (
    <div
      style={{
        gridArea,
        position: "relative",
        overflow: "hidden",
        ...((style as React.CSSProperties) || {}),
      }}
    >
      <PanelSizeProvider size={{ width: cellW, height: cellH }}>
        <AnyComponent {...componentProps} />
      </PanelSizeProvider>
    </div>
  );
};

// ---------------------------------------------------------------------------
// SceneWrapper — renders header + grid of panels + transition overlay
// ---------------------------------------------------------------------------

const autoDelay = (index: number, total: number, duration: number) => {
  // If only one panel, show immediately
  if (total <= 1) return 0;
  // Distribute evenly so panel i starts at duration/total * i
  return Math.floor((duration / total) * index);
};

const SceneWrapper: React.FC<{
  scene: SceneSpec;
  videoWidth: number;
  videoHeight: number;
  hasCaptions: boolean;
  baseDuration: number;
  crossfade: number;
}> = ({ scene, videoWidth, videoHeight, hasCaptions, baseDuration, crossfade }) => {
  const sceneFrame = useCurrentFrame();
  const { layout, title, panels } = normaliseScene(scene);
  // Smooth cross-dissolve: fade the whole scene in at the start, and out over the
  // crossfade tail (the extra frames that overlap the next scene). Pure opacity is
  // the least-noticeable transition and keeps audio/caption timing untouched.
  const fadeIn = interpolate(sceneFrame, [0, 14], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const fadeOut =
    crossfade > 0
      ? interpolate(sceneFrame, [baseDuration, baseDuration + crossfade], [1, 0], {
          extrapolateLeft: "clamp",
          extrapolateRight: "clamp",
        })
      : 1;
  const sceneOpacity = Math.min(fadeIn, fadeOut);
  const config = LAYOUTS[layout] ?? LAYOUTS["full"];
  // Only render the header bar when there is an actual title, so title-less
  // scenes don't waste 148px on an empty bar.
  const showHeader = config.hasHeader && title.trim().length > 0;
  // Reserve the subtitle band only when the video has captions.
  const subtitleReserve = hasCaptions
    ? Math.round(videoHeight * SUBTITLE_RESERVE_FRAC)
    : 0;
  const contentH =
    (showHeader ? videoHeight - HEADER_H : videoHeight) - subtitleReserve;
  const hasDiagram = panels.some((p) => DIAGRAM_TYPES.has(p.type));

  // Column fractions per grid area (honors explicit size_ratio, else infers from
  // component category — see layout.ts) and the deterministic per-area pixel width
  // (gap is 0) so each panel can scale its component to fit without a ResizeObserver.
  const rowStr = config.gridTemplateAreas.replace(/"/g, "").trim();
  const areaNames = rowStr.split(/\s+/);
  const frByArea = computeFractions(areaNames, panels);
  const dynamicColumns =
    areaNames.length > 1
      ? areaNames.map((a) => `${frByArea[a]}fr`).join(" ")
      : config.gridTemplateColumns;
  const cellWByArea = cellWidths(areaNames, frByArea, videoWidth);

  return (
    <AbsoluteFill style={{ opacity: sceneOpacity }}>
      {/* Animated theme-driven background (behind everything) */}
      <Background variant={hasDiagram ? "grid" : "glow"} />
      {/* Content above the background — bottom padding reserves the subtitle band */}
      <AbsoluteFill
        style={{
          flexDirection: "column",
          zIndex: 1,
          paddingBottom: subtitleReserve,
          boxSizing: "border-box",
        }}
      >
        {/* Header bar (only when there is a title) */}
        {showHeader && <SceneHeader title={title} subtitle={scene.subtitle} />}

        {/* Content grid */}
        <div
          style={{
            flex: 1,
            height: contentH,
            display: "grid",
            gridTemplateAreas: config.gridTemplateAreas,
            gridTemplateColumns: dynamicColumns,
            gridTemplateRows: config.gridTemplateRows,
            gap: 0,
          }}
        >
          {panels.map((panel, index) => (
            <Sequence
              key={panel.area}
              from={
                panel.delay_frames != null && panel.delay_frames > 0
                  ? panel.delay_frames
                  : autoDelay(index, panels.length, scene.duration_frames)
              }
              layout="none"
            >
              <PanelCell
                panel={panel}
                gridArea={panel.area}
                cellW={cellWByArea[panel.area] ?? videoWidth}
                cellH={contentH}
              />
            </Sequence>
          ))}
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

// ---------------------------------------------------------------------------
// DynamicVideo — top-level composition
// ---------------------------------------------------------------------------

export const DynamicVideo: React.FC<VideoScriptProps> = ({
  width,
  height,
  theme,
  scenes,
  voiceover,
  audio_url,
}) => {
  // Frames each scene lingers past its end to dissolve into the next. Only the
  // Sequence duration is extended (they overlap) — `from` stays on the exact
  // cumulative timeline, so audio + captions are never shifted.
  const CROSSFADE = 18;
  let cursor = 0;
  const positioned = scenes.map((scene, i) => {
    const from = cursor;
    cursor += scene.duration_frames;
    return { scene, from, isLast: i === scenes.length - 1 };
  });
  const hasCaptions = (voiceover?.captions?.length ?? 0) > 0;

  return (
    <ThemeProvider theme={theme}>
      <AbsoluteFill style={{ backgroundColor: theme.background }}>
        {positioned.map(({ scene, from, isLast }) => (
          <Sequence
            key={scene.id}
            from={from}
            durationInFrames={scene.duration_frames + (isLast ? 0 : CROSSFADE)}
            premountFor={30}
          >
            <SceneWrapper
              scene={scene}
              videoWidth={width}
              videoHeight={height}
              hasCaptions={hasCaptions}
              baseDuration={scene.duration_frames}
              crossfade={isLast ? 0 : CROSSFADE}
            />
          </Sequence>
        ))}

        {/* Global TTS Audio */}
        {audio_url && <Audio src={`http://127.0.0.1:8000${audio_url}`} />}

        {/* On-screen textual explanation (narration), synced to the absolute timeline */}
        <CaptionLayer captions={voiceover?.captions} />
      </AbsoluteFill>
    </ThemeProvider>
  );
};
